server.port=8080
spring.thymeleaf.cache=false

# Python API location
pipeline.api.base-url=http://localhost:8000

# Sample CSV files read by Java UI
pipeline.sample.auth-path=../data/sample/auth_linux_sample.csv
pipeline.sample.net-path=../data/sample/network_ids_sample.csv
